= Rappels Git

== Configuration recommandée
* `git config --global user.name "John Doe"` renseigne le nom de l'utilisateur utilisé dans les commits.
* `git config --global user.email johndoe@example.fr` renseigne l'email de l'utilisateur utilisé dans les commits.
* `git config --global push.default current` utilise par défaut le même nom de branche pour le remote.

== Les titres de commits
Ces titres sont la plupart du temps lus par d'autres personnes que l'auteur et doivent aider à comprendre l'**intention** derrière la modification.
L'**intention** reflète le **pourquoi** et non le comment.
Le *comment* n'a pas d'intérêt comme titre, car il est directement disponible dans les fichiers modifiés.

On estime qu'un bon titre de commit commence par une majuscule, un verbe, et ne dépasse pas 50 caractères.

Il peut être nécessaire d'apporter des éléments de contexte ou des explications.
Dans ce cas, une description peut être ajoutée au titre après avoir sauté une ligne.

Plus d'informations peuvent être trouvées ici : https://chris.beams.io/posts/git-commit/

== Commandes
* `git clone <url>` clone un dépôt distant
* `git status` affiche l'état du dossier de travail
* `git log --oneline` affiche l'historique de la branche courante (du plus récent au plus vieux)
** `git --no-pager log --oneline -n 10` affiche les 10 derniers commits de la branche courante
* `git fetch --all --prune` récupère la base de données Git du remote (ne change pas le répertoire de travail)

* `git add <file>` indexe un fichier
** `git add <folder>` indexe toutes les modifications dans le répertoire indiqué
** `git add .` indexe toutes les modifications
* `git reset <file>` désindexe un fichier

* `git commit -m "<titre>"` crée un commit avec les modifications indexées et le titre indiqué
** `git commit` crée un commit avec les modifications indexées et le message renseigné dans l'éditeur qui est alors ouvert

* `git checkout <branch_name>` bascule sur la branche indiquée
** `git checkout -b <branch_name>` crée une nouvelle branche et bascule dessus
* `git branch -D <branch_name>` supprime la branche indiquée

* `git push` publie la branche courante sur le remote
** `git push --force-with-lease` écrase la branche distante avec l'historique local

* `git rebase origin/<branch_name>` rebase la branche courante par rapport à sa version distante, c'est-à-dire déplace les commits locaux après les derniers commits distants
** Cette commande est préférable à un *merge*, car elle ne crée pas de commit supplémentaire
** Elle permet de retrouver le statut **fast-forward** d'une branche, c'est-à-dire de n'avoir que des commits **en plus** par rapport à la branche distante
** En cas de conflit, le *rebase* s'arrête sur chaque commit conflictuel
*** Une fois les conflits résolus (marqués comme tels avec `git add <conflicting_file>`), le *rebase* peut être continué avec la commande `git rebase --continue`
*** Si la résolution de conflit mène à une absence de changement, le commit peut être sauté avec `git rebase --skip`
*** Pendant un *rebase*, il est toujours possible de revenir à l'état d'avant le début du *rebase* avec `git rebase --abort`

* `git commit --amend` modifie le dernier commit en y ajoutant les fichiers indexés, sans créer un nouveau commit
** `git commit --amend --no-edit` modifie le dernier commit en y ajoutant les fichiers indexés sans changer le message du commit
** ⚠️ En modifiant un commit qui a été publié sur le remote, la branche locale diverge. Il faudra utiliser `git push --force-with-lease` pour écraser la version distante

* `git rebase -i <sha>` retravaille l'historique sur les commits après celui dont le **sha** est indiqué
** Le **sha** des commits peut être visualisé avec la commande `git log --oneline`
** Ce type de *rebase*, dit *rebase interactif*, permet pour chaque commit sélectionné de :
*** modifier les modifications
*** renommer les messages
*** changer l'ordre
*** le fusionner avec un autre commit
*** le supprimer
