= Exercice sur Git
:tip-caption: 💡
:note-caption: ℹ️
:warning-caption: ⚠️
:icons: font
:hardbreaks-option:

La correction est automatique, prêtez donc une attention spéciale aux messages de commit, aux noms des branches, etc.

Tous les fichiers que vous indexerez doivent avoir une ligne vide à la fin (en plus du contenu donc).

Les fichiers avec l'extension `.md` sont au format https://guides.github.com/features/mastering-markdown[Markdown].

Préfixé par ✔️, des "checkpoints" pour vous aider à vérifier que vous avez tout bon.

Les commits non modifiés d'une partie à l'autre doivent avoir le même ID (hash).

Les parties sont notées sur 1 point, le total sur 4 points.

Si une partie n'est pas faite en intégralité, la note de cette partie sera 0.

Les parties se suivent et sont à faire dans l'ordre.

== Prérequis

* Git
** Configurer Git avec votre nom et email :
*** `git config --global user.name "John Doe"`
*** `git config --global user.email johndoe@example.fr`
** De préférence, générer une clé SSH (si absente) et donner la partie publique à GitHub (cf https://help.github.com/articles/connecting-to-github-with-ssh/), afin de pouvoir cloner le dépôt avec l'*url SSH*

'''

Rappels des commandes de base : link:CHEATSHEET_fr.adoc[]

== Partie 1

* Créer un nouveau dépôt Git privé (bouton radio *private* dans le formulaire) sur la plateforme GitHub avec le nom *git_training* initialisé avec un fichier `README.md` (case à cocher dans le formulaire)
* Cloner ce nouveau dépôt en utilisant l'*url SSH*
* Créer une nouvelle branche nommée *ex/part_1*
* Ajouter un fichier nommé `Doc.md` et contenant un titre *Documentation* et un lien hypertexte nommé *Git - Documentation* pointant sur https://git-scm.com/doc
* ✔️ ce fichier doit donc faire 3 lignes, une pour le titre, une pour le lien, puis une ligne vide
* Commiter ce fichier avec le message *Add Git documentation*
* Ajouter un fichier nommé `Ex.md` et contenant le titre *Exercice* et un bullet point avec le texte *Part 1*
* Commiter ce fichier avec le message *Setup exercise file*
* Modifier le fichier `Doc.md` en ajoutant à la fin un lien hypertexte nommé *Markdown - Documentation* et pointant sur https://guides.github.com/features/mastering-markdown
* Commiter ce changement avec le message *Add Markdown doc*
* ✔️ cette branche a donc 4 commits en tout (Initial commit + les 3 que vous venez de faire)
* Pousser la branche (sur votre remote par défaut, en l'occurrence GitHub)

== Partie 2

* Créer une nouvelle branche nommée *ex/part_2* à partir de la branche précédente
* Pousser cette branche
* Modifier le dernier message de commit pour donner *Add Markdown documentation*
* Modifier le dernier commit en ajoutant à la fin du fichier `Doc.md` un nouveau lien hypertexte appelé *Markdown bestpractices* et pointant sur https://www.markdownguide.org/basic-syntax
* ✔️ à ce stade, cette branche a 4 commits en tout et elle a divergé par rapport à la version du remote
* Pousser la branche
* Ajouter dans le fichier `Ex.md` un nouveau bullet point avec le texte *Part 2*
* Commiter avec le message *Ex Part 2*
* Pousser la branche

== Partie 3

* Créer une nouvelle branche nommée *ex/part_3* à partir de la branche précédente
* Modifier le fichier `Ex.md` en ajoutant un bullet point avec le texte *Part 3*
* Commiter ce changement
* Regrouper les commits sur la documentation en 1 seul commit avec comme message *Add documentation*
* Regrouper les commits sur le fichier `Ex.md` en 1 seul commit avec comme message *Exercise*
* ✔️ à ce stade, cette branche a 3 commits (Initial commit + les deux commits gardés sur cette partie)
* Pousser la branche

== Partie 4

* Créer une nouvelle branche nommée *ex/part_4* à partir de la branche précédente
* Ajouter un fichier `End.md` avec le titre *The end*
* Commiter ce fichier avec le message *Back to the future*
* Déplacer ce commit entre le commit sur la documentation et celui sur le fichier `Ex.md`
* ✔️ vous devriez avoir les commits suivants (ce que vous pouvez voir avec `git log --oneline`)
** Exercise
** Back to the future
** Add documentation
** Initial commit
* Pousser la branche
